name: "Lint PR"

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

permissions:
  contents: read

jobs:
  check-pr-title:
    name: Validate PR title
    runs-on: ubuntu-24.04
    permissions:
      pull-requests: write
    steps:
      - uses: amannn/action-semantic-pull-request@24e6f016c1e110f5353026c0b6129a4118b9146c # v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
